variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  VERSIONING_DISABLE: "false"
  VERSIONING_GIT_TAG: $CI_COMMIT_TAG
  VERSIONING_GIT_BRANCH: $CI_COMMIT_BRANCH

default:
  cache:
    paths:
      - .m2/repository/
  tags:
    - qlf-ci.inria.fr

stages:
  - build
  - deploy

build:
  image: maven:3.8.1-adoptopenjdk-11
  stage: build
  script:
    - mvn -B -s .mvn/settings-ci.xml -ntp -fae -DdeployAtEnd spotless:check deploy
  artifacts:
    paths:
      - "**/target/*.jar"
      - "**/target/cucumber-reports/Cucumber.html"
    reports:
      junit:
        - "**/target/surefire-reports/TEST-*.xml"

deploy_int:
  stage: deploy
  variables:
    APP_VERSION: develop-SNAPSHOT
  trigger:
    project: stemcovid19/infrastructure/functional-zone/services/codegeneration/codegeneration-ansible
    branch: feature/gitlab-ci
    strategy: depend
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/trigger-deploy"'
