include:
  - project: stopcovid19/accueil
    ref: master
    file: gitlab/gitlab-ci-java-template.yml

build-docker:
  image: maven:3.8.3-adoptopenjdk-11
  stage: build
  needs: ["build"]
  tags:
    - caascad
  script:
    # Build image and push to container registry
    - mvn -B spring-boot:build-image
      -Dmaven.test.skip=true
      -Dspring-boot.build-image.imageName=$K8S_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      -Dspring-boot.build-image.publish=true
      -Dspring-boot.build-image.publishRegistry.username=$K8S_REGISTRY_USER
      -Dspring-boot.build-image.publishRegistry.password=$K8S_REGISTRY_PASSWORD
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

deploy-int:
  stage: deploy
  variables:
    APP_VERSION: develop-SNAPSHOT
  trigger:
    project: stemcovid19/infrastructure/functional-zone/services/codegeneration/codegeneration-ansible
    branch: master
    strategy: depend
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

publish-deployment:
  stage: publish
  variables:
    ENVIRONMENT: "int"
  script:
    - cd ./src/k8s/base
    - kustomize edit set image submission-image=$K8S_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - kustomize build . > /tmp/deployments/$ENVIRONMENT/deployment.yml
    - cd /tmp/deployments
    - git add ./$ENVIRONMENT/deployment.yml
    - git commit -m "$CI_COMMIT_SHORT_SHA"
    - git push origin master
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
