include:
  - project: stopcovid19/accueil
    ref: master
    file: gitlab/gitlab-ci-java-template.yml

build-v1:
  image: maven:3.8.3-adoptopenjdk-11
  stage: build
  before_script:
    - cd legacy-submission-code-server
  script:
    - mvn -B -s .mvn/settings-ci.xml $CI_MAVEN_OPTS deploy
  artifacts:
    paths:
      - "**/target/"
    reports:
      junit:
        - "**/target/*-reports/TEST-*.xml"

deploy-int:
  stage: deploy
  variables:
    APP_VERSION: develop-SNAPSHOT
  trigger:
    project: stemcovid19/infrastructure/functional-zone/services/codegeneration/codegeneration-ansible
    branch: master
    strategy: depend
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
