include:
  - project: stopcovid19/accueil
    ref: master
    file: gitlab/gitlab-ci-java-template.yml

build-v2:
  image: maven:3.8.3-adoptopenjdk-11
  stage: build
  script:
    - mvn -B -s .mvn/settings-ci.xml -f legacy-submission-code-server/pom.xml -Dspring-boot.repackage.skip=true $CI_MAVEN_OPTS install
    - mvn -B -s .mvn/settings-ci.xml $CI_MAVEN_OPTS deploy
  artifacts:
    paths:
      - "**/target/"
    reports:
      junit:
        - "**/target/*-reports/TEST-*.xml"
  tags:
    - ci.inria.fr
    - medium

build:
  before_script:
    - cd legacy-submission-code-server

quality:
  variables:
  before_script:
    - cd legacy-submission-code-server
    - sed -i 's/>legacy-submission/>submission/g' pom.xml

owasp:
  before_script:
    - cd legacy-submission-code-server

deploy-int:
  stage: deploy
  variables:
    APP_VERSION: develop-SNAPSHOT
  trigger:
    project: stemcovid19/infrastructure/functional-zone/services/codegeneration/codegeneration-ansible
    branch: master
    strategy: depend
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
