include:
  - project: stopcovid19/accueil
    ref: master
    file: gitlab/gitlab-ci-java-template.yml

build-v1:
  image: maven:3.8.3-adoptopenjdk-11
  stage: build
  before_script:
    - cd legacy-submission-code-server
  script:
    - mvn -B -s .mvn/settings-ci.xml $CI_MAVEN_OPTS deploy
  artifacts:
    paths:
      - "**/target/"
    reports:
      junit:
        - "**/target/*-reports/TEST-*.xml"

build:
  script:
    # Build image and push to container registry
    - mvn spring-boot:build-image -Dmaven.test.skip=true -Dspring-boot.build-image.imageName=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -Dspring-boot.build-image.publish=true
