include:
  - project: stopcovid19/accueil
    ref: master
    file: gitlab/gitlab-ci-java-template.yml

deploy-int:
  stage: deploy
  variables:
    APP_VERSION: develop-SNAPSHOT
  trigger:
    project: stemcovid19/infrastructure/functional-zone/services/codegeneration/codegeneration-ansible
    branch: master
    strategy: depend
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
