include:
  - project: stopcovid19/accueil
    ref: master
    file: gitlab/gitlab-ci-java-template.yml

build-docker:
  image: maven:3.8.3-adoptopenjdk-11
  stage: build
  needs: ["build"]
  tags:
    - caascad
  script:
    # Build image and push to container registry
    - mvn -B spring-boot:build-image
      -Dmaven.test.skip=true
      -Dspring-boot.build-image.imageName=$K8S_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      -Dspring-boot.build-image.publish=true
      -Dspring-boot.build-image.publishRegistry.username=$K8S_REGISTRY_USER
      -Dspring-boot.build-image.publishRegistry.password=$K8S_REGISTRY_PASSWORD
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

deploy-int:
  stage: deploy
  variables:
    APP_VERSION: develop-SNAPSHOT
  trigger:
    project: stemcovid19/infrastructure/functional-zone/services/codegeneration/codegeneration-ansible
    branch: master
    strategy: depend
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

deployment:
  image:
    name: alpine
  stage: deploy
  tags:
    - caascad
  variables:
    KUSTOMIZE_VER: "4.5.7"
    ENVIRONMENT: "int"
  before_script:
    - apk add --no-cache openssh-client-default git
    - wget -O - https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v${KUSTOMIZE_VER}/kustomize_v${KUSTOMIZE_VER}_linux_amd64.tar.gz | tar xz -C /usr/local/bin
    - eval $(ssh-agent -s)
    - echo "$GIT_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - >/dev/null
    - mkdir -p ~/.ssh
    - cp $SSH_KNOWN_HOSTS ~/.ssh/known_hosts
    - chmod 700 ~/.ssh
    - chmod 600 ~/.ssh/known_hosts
  script:
    - git config --global user.name  "$CI_COMMIT_SHORT_SHA"
    - git config --global user.email "$CI_COMMIT_SHORT_SHA"
    - git clone --branch master git@${GIT_REPOSITORY_URL} /tmp/submission-app
    - cd ./src/k8s
    - kustomize edit set image submission-server=$K8S_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - kustomize build . > /tmp/submission-app/deployment-$ENVIRONMENT.yml
    - cd /tmp/submission-app
    - git add ./deployment-$ENVIRONMENT.yml
    - git commit -m "$ENVIRONMENT $CI_COMMIT_SHORT_SHA"
    - git push origin master
  rules:
    - if: $CI_COMMIT_BRANCH == 'develop'
