apiVersion: apps/v1
kind: Deployment
metadata:
  name: submission-code-server-deployment
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: submission-code-server
  template:
    metadata:
      labels:
        app: submission-code-server # Bind by service selector>app:
    spec:
      containers:
        - name: submission-app
          image: submission-server
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: submission-secrets
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: submission-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SUBMISSION_JWTPUBLICKEYS_TOUSANTICOVIDKID
              valueFrom:
                secretKeyRef:
                  name: submission-secrets
                  key: SUBMISSION_JWTPUBLICKEYS_TOUSANTICOVIDKID
            - name: SPRING_DATASOURCE_USERNAME
              value: pocinit
            - name: SPRING_FLYWAY_ENABLED
              value: "true"
            - name: SPRING_FLYWAY_BASELINE_ON_MIGRATE
              value: "true"
            - name: SPRING_FLYWAY_BASELINE_VERSION
              value: "0"
      nodeSelector:
        cce.cloud.com/cce-nodepool: "caascad-inttac-ju-pod-tac-dashing-boa"
      imagePullSecrets:
        - name: poc-inttac-poc-img-push-pull-secret
