apiVersion: v1
kind: Service
metadata:
  name: submission-code-server-service # Service name
spec:
  type: NodePort # Sets the service type
  selector:
    app: submission-code-server # Defines app that will be targeted
  ports:
    - port: 80
      targetPort: 8080
