openapi: 3.0.0
info:
  title: Submission Code Server API
  version: "1"
  description: |
    Submission Code Server API Spec.
    Submission codes are _one-time-codes_ to declare themself ill.
    NOTE: This API is protected and used only by a trusted back-end server over a secure private connection.
  termsOfService: https://gitlab.inria.fr/stopcovid19/submission-code-server
  contact:
    email: stopcovid@inria.fr
  license:
    name: Custom (see repository's LICENSE.md)
paths:
  /verify:
    get:
      operationId: verify
      tags:
        - Submission Code
      summary: Verify a code and prevent further use
      description: Check the validity of a submission code (originally provided by the app).
      parameters:
        - name: deprecatedCodeType
          in: query
          required: false
          description: Deprecated field
          schema:
            type: integer
        - name: code
          in: query
          required: true
          description: |
            The submission code (as a JWT) to validate. :
            A JWT has three parts : a header, a payload and a signature
            header {
              "alg": "ES256",
              "kid": "D99DA442",
              "typ": "JWT"
            }
            payload {
              "iat": "2022-01-01T00:00:00Z",
              "iss": "SIDEP",
              "jti": "123456789ABCDEF"
            }

            See example response for invalid code format.
          schema:
            type: string
      responses:
        200:
          description: Returns the submission code validation result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubmissionCodeValidationResponse"
              examples:
                valid code:
                  value:
                    valid: true
                valid but expired code:
                  value:
                    valid: false
                "invalid code format (ex: z/zzz)":
                  value:
                    valid: false
        400:
          $ref: "openapi-errors-v1.yml#/components/responses/BadRequest"
        401:
          $ref: "openapi-errors-v1.yml#/components/responses/Unauthorized"
        403:
          $ref: "openapi-errors-v1.yml#/components/responses/Forbidden"
        500:
          $ref: "openapi-errors-v1.yml#/components/responses/InternalServerError"

  /kpi:
    get:
      operationId: kpi
      tags:
        - Kpi
      summary: Get KPIs
      description: Get KPIs for the given period
      parameters:
        - name: fromDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: toDate
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        200:
          description: Returns the KPI list for date range
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KpisResponse"
        400:
          $ref: "openapi-errors-v1.yml#/components/responses/BadRequest"
        401:
          $ref: "openapi-errors-v1.yml#/components/responses/Unauthorized"
        403:
          $ref: "openapi-errors-v1.yml#/components/responses/Forbidden"
        500:
          $ref: "openapi-errors-v1.yml#/components/responses/InternalServerError"

components:
  schemas:
    SubmissionCodeValidationResponse:
      type: object
      properties:
        valid:
          type: boolean
          description: True if the code is valid, false if invalid or expired
      required:
        - valid

    KpisResponse:
      type: array
      items:
        $ref: "#/components/schemas/Kpi"

    Kpi:
      type: object
      properties:
        date:
          type: string
          format: date
        nbJwtUsed:
          type: integer
          format: int64
          example: 45
      required:
        - date
        - nbJwtUsed
