openapi: 3.0.0
info:
  description:
    Submission Code Server Client API Spec. This server generates one-time codes
    to be used in the StopCovid app.
  version: 0.0.1
  title: Submission Code Server Client API Spec
  termsOfService: https://gitlab.inria.fr/stopcovid19/submission-code-server
  contact:
    email: stopcovid@inria.fr
  license:
    name: Custom (see repository's LICENSE.md)
paths:
  "/generate/short":
    get:
      tags:
        - Generate Code
      summary: Generate 6-alphanum code
      description: Generate a new submission code. Codes are usable once.
      operationId: generate
      responses:
        "200":
          description: Generated code
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CodeSimpleDto"
  "/generate/test":
    get:
      tags:
        - Generate Code
      summary: Generate a test code that is 12 characters long.
      description: Generate a new submission code. Codes are usable once.
      operationId: generateTest
      responses:
        "200":
          description: Generated code
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CodeSimpleDto"
  "/verify":
    get:
      tags:
        - Verify Code
      summary: Verify a code
      description: >-
        Check the validity of a submission code (originally provided by the
        app).

        NOTE: This API must be protected and used only by a trusted back-end server over a secure private connection.
      operationId: verify
      parameters:
        - name: type
          in: query
          required: false
          description: If present, should respect regex ({1-3}1)
          schema:
            type: string
        - name: code
          in: query
          required: true
          description: should respect regexp ([a-zA-Z0-9]{6}) |
            ([a-f0-9]{8}(-[a-f0-9]{4}){4}[a-f0-9]{8}) | ([a-zA-Z0-9]{12})
          schema:
            type: string
      responses:
        "200":
          description: Returns the submission code validation result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VerifyDto"
  "/kpi":
    servers:
      - url: mycodeserver.org/intenal/api/v1
    get:
      tags:
        - KPI
      summary: Get KPIs
      description: >-
        Get KPIs concerning input time range

        NOTE: This API must be protected and used only by a trusted back-end server over a secure private connection.
      operationId: kpi
      parameters:
        - name: fromDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: toDate
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        "200":
          description: Returns the KPI list for date range
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KpisResponse"
components:
  schemas:
    CodeDetail:
      type: object
      properties:
        code:
          type: string
    KpisResponse:
      type: array
      items:
        $ref: "#/components/schemas/Kpi"
    Kpi:
      type: object
      properties:
        date:
          type: string
          format: date
        nbShortCodesUsed:
          type: integer
          format: int64
        nbLongCodesUsed:
          type: integer
          format: int64
        nbLongExpiredCodes:
          type: integer
          format: int64
        nbShortExpiredCodes:
          type: integer
          format: int64
        nbShortCodesGenerated:
          type: integer
          format: int64
      required:
        - date
        - nbShortCodesUsed
        - nbLongCodesUsed
        - nbLongExpiredCodes
        - nbShortExpiredCodes
        - nbShortCodesGenerated
    VerifyDto:
      type: object
      properties:
        valid:
          type: boolean
          description: >-
            True if the code is valid, false if invalid or expired, or if type
            does not match an existing code.

            A valid code is destroyed when validated successfully.
      required:
        - valid
    CodeSimpleDto:
      type: object
      properties:
        code:
          type: string
          description:
            The submission code to display. Should be encoded as a QR code by
            the client (combined with type info).
          example: AS3F5Z
          pattern: "[a-zA-Z0-9]{6}"
        validFrom:
          type: string
          description:
            Submission code must not be used before this validity date.
            Format ISO date is YYYY-MM-DDTHH:mm:ss.sssZ
        validUntil:
          type: string
          description:
            Submission code must not be used after this validity date.
            Format ISO date is YYYY-MM-DDTHH:mm:ss.sssZ
        dateGenerate:
          type: string
          description: Format ISO date is YYYY-MM-DDTHH:mm:ss.sssZ
      description: A submission code and its type as well as validity information
      required:
        - code
        - validFrom
        - validUnti
