#!/usr/bin/env bash

# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>

# This hook prevent push of commits where the author or commiter isn't pseudonymised

ALLOW_LIST="
Ananas Orange <12847-x-AOrang@users.noreply.gitlab.inria.fr>
Bergamote Orange <13178-x-BOrang@users.noreply.gitlab.inria.fr>
Combava Orange <13340-x-CoOrang@users.noreply.gitlab.inria.fr>
Framboise Orange <12541-x-FrOrang@users.noreply.gitlab.inria.fr>
Jujube Orange <13631-x-JOrang@users.noreply.gitlab.inria.fr>
Kiwi Orange <13476-x-KOrang@users.noreply.gitlab.inria.fr>
Cacaoyer Tac <99999-Cacaoyer.tac@users.noreply.gitlab.inria.fr>
Cafeier Tac <99999-Cafeier.tac@users.noreply.gitlab.inria.fr>
Caladium Tac <99999-Caladium.tac@users.noreply.gitlab.inria.fr>
Calamagrostis Tac <99999-Calamagrostis.tac@users.noreply.gitlab.inria.fr>
Calament Tac <99999-Calament.tac@users.noreply.gitlab.inria.fr>
Calamondin Tac <99999-Calamondin.tac@users.noreply.gitlab.inria.fr>
Calanthe Tac <99999-Calanthe.tac@users.noreply.gitlab.inria.fr>
Calibrachoa Tac <99999-Calibrachoa.tac@users.noreply.gitlab.inria.fr>
Jenkins Tac <99999-Jenkins.tac@users.noreply.gitlab.inria.fr>
Figue Orange <12540-x-FOrang@users.noreply.gitlab.inria.fr>
"

remote="$1"
url="$2"

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

while read local_ref local_oid remote_ref remote_oid
do
  if test "$local_oid" = "$zero"
  then
    # Nothing to to on branch deletion
    :
  else
    if test "$remote_oid" = "$zero"
    then
      # New branch, examine all commits
      range="5bb417c3..$local_oid"
    else
      # Update to existing branch, examine new commits
      range="$remote_oid..$local_oid"
    fi
    echo -n "Checking the author/commiter is in the allowed list ($0) "
    for format in '%an <%ae>' '%cn <%ce>'
    do 
      while read -r user
      do
        allowed_user=$(grep "^$user$" <<<$ALLOW_LIST)
        if test ! -n "$allowed_user"
        then
          echo "❌"
          echo >&2 "'$user' is not allowed in $local_ref, not pushing"
          exit 1
        fi
      done <<<$(git log --format="format:$format" $range | sort | uniq)
    done
    echo "✅"
  fi
done

exit 0
