apiVersion: apps/v1
kind: Deployment
metadata:
  name: submission-code-server-deployment
  labels:
    app: submission-code
spec:
  selector:
    matchLabels:
      app: submission-code-server
  template:
    metadata:
      labels:
        app: submission-code-server
    spec:
      containers:
        - name: submission-app
          image: submission-image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: submission-secrets
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: submission-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SUBMISSION_JWTPUBLICKEYS_TOUSANTICOVIDKID
              valueFrom:
                secretKeyRef:
                  name: submission-secrets
                  key: SUBMISSION_JWTPUBLICKEYS_TOUSANTICOVIDKID
            - name: SPRING_DATASOURCE_USERNAME
              value: pocinit
            - name: SPRING_FLYWAY_ENABLED
              value: "true"
            - name: SPRING_FLYWAY_BASELINE_ON_MIGRATE
              value: "true"
            - name: SPRING_FLYWAY_BASELINE_VERSION
              value: "0"
      nodeSelector:
        caascad.io/nodepool: "pod-tac"
      imagePullSecrets:
        - name: poc-inttac-poc-img-push-pull-secret
