apiVersion: apps/v1
kind: Deployment
metadata:
  name: submission-code-server-deployment
  labels:
    app: submission-code
spec:
  selector:
    matchLabels:
      app: submission-code-server
  template:
    metadata:
      labels:
        app: submission-code-server
    spec:
      initContainers:
        - name: robert-submission-db-initializer
          image: flyway-image
          command: ["flyway", "migrate"]
          env:
            - name: FLYWAY_BASELINE_ON_MIGRATE
              value: "true"
            - name: FLYWAY_BASELINE_VERSION
              value: "0"
            - name: FLYWAY_USER
              value: pocinit
            - name: FLYWAY_URL
              valueFrom:
                secretKeyRef:
                  name: submission-secrets
                  key: SPRING_DATASOURCE_URL
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: submission-secrets
                  key: SPRING_DATASOURCE_PASSWORD
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 750Mi
      containers:
        - name: submission-app
          image: submission-image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                secretKeyRef:
                  key: SPRING_APPLICATION_JWTPUBLICKEYS_JSON
                  name: submission-secrets
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: submission-secrets
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: submission-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_DATASOURCE_USERNAME
              value: pocinit
            - name: MANAGEMENT_SERVER_PORT
              value: "8081"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: health,info,prometheus
      nodeSelector:
        caascad.io/nodepool: "pod-tac"
      imagePullSecrets:
        - name: poc-inttac-poc-img-push-pull-secret
