apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: submission-code-hpa
  labels:
    app: submission-code
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: submission-code-server-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
