apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: submission-code-logs-role
  namespace: submission-code
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: submission-code-logs
subjects:
  - kind: ServiceAccount
    name: default
    namespace: robert-e2e-tests
