apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: submission-code-logs
  namespace: submission-code
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
