apiVersion: v1
kind: Service
metadata:
  labels:
    app: submission-code
  name: submission-code-server-service
spec:
  type: NodePort
  selector:
    app: submission-code-server
  ports:
    - port: 80
      targetPort: 8080
