apiVersion: v1
kind: Service
metadata:
  labels:
    app: submission-code
  name: submission-code-server-service
  namespace: submission-code
spec:
  selector:
    app: submission-code-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: management
      port: 8081
      targetPort: 8081
      protocol: TCP
