apiVersion: v1
kind: Service
metadata:
  labels:
    app: submission-code # do not delete, used for billing
  name: submission-code-server-service # Service name
spec:
  type: NodePort
  selector:
    app: submission-code-server # Defines app that will be targeted
  ports:
    - port: 80
      targetPort: 8080
